import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// * GET Server Side Props

// export const getServerSideProps = async (context) => {
//   console.log(context);

//   const response = await fetch("https://api.quotable.io/random");
//   const quotes = await response.json();

//   console.log(quotes);

//   return {
//     props: {
//       quotes
//     },
//   };
// };

export default function Home() {
  // Env Variable
  console.log("Secret Variable = ", process.env.SECRET_VARIABLE);

  // Browser Output ->  Secret Variable =  undefined
  // Server Side Output -> Secret Variable =  somthing very secret

  // Env Variable

  console.log(
    "Nextjs Secret Variable = ",
    process.env.NEXT_PUBLIC_FIRST_VARIABLE
  );

  // Browser Output ->  Nextjs Secret Variable =  Hello Nexjs (Expose on browser Console)
  // Server Side Output -> Nextjs Secret Variable =  Hello Nexjs

  // *Server Side Props
  // console.log(`Title : ${props.title}  and Description : ${props.description}`);
  // console.log(quotes)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>{/*quotes.content*/}</h2>
            <p>{/*quotes.author*/}</p>
          </a>
      

       
        
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
